version: "3.1"

# API ports
# 8080 | Products
# 8083 | Orders

# Mongo express ports
# 8082 | Products
# 8085 | Orders

services:
  # Kong API Gateway
  kong:
    image: kong
    restart: always
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
    environment:
      KONG_DATABASE: "off"  # Use in-memory datastore for development
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong.yml:/etc/kong/kong.yml  # Mount the Kong configuration file
    depends_on:
      - product-service
      - order-service
    command: kong start -c /etc/kong/kong.yml

  # Products ----------------------------------------------------------------
  product-service:
    build:
      context: ../product-service/src/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ProductDatabase__ConnectionString=mongodb://root:example@product-mongo:27017/
    ports:
      - "8080:80"
      - "8081:443"

  product-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  product-mongo-express:
    depends_on:
      - product-mongo
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@product-mongo:27017/

  # Orders ----------------------------------------------------------------

  order-service:
    build:
      context: ../order-service/src/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OrderDatabase__ConnectionString=mongodb://root:example@order-mongo:27017/
    ports:
      - "8083:80"
      - "8084:443"

  order-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  order-mongo-express:
    depends_on:
      - order-mongo
    image: mongo-express
    restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@order-mongo:27017/
